### ISSUE TITLE
Using podman dockerBuildAndPush error Could not parse Docker image

### ISSUE THREAD

**Issue by demitov** [marcuslonnberg/sbt-docker#134]
I have installed Podman in k8s container, and create symlink /usr/bin/docker -> /usr/bin/podman. When execute dockerBuildAndPush I get an error, because Podman don't return digest after podman push.

[error] sbtdocker.DockerPushException: Could not parse Docker image digest
[error]   at sbtdocker.DockerPush$.apply(DockerPush.scala:61)
[error]   at sbtdocker.DockerPush$.$anonfun$apply$1(DockerPush.scala:18)
[error]   at scala.collection.immutable.List.map(List.scala:293)
[error]   at sbtdocker.DockerPush$.apply(DockerPush.scala:17)
[error]   at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$2(DockerSettings.scala:26)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]   at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]   at sbt.Execute.work(Execute.scala:291)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]   at java.base/java.lang.Thread.run(Thread.java:829)
[error] (dockerPush) sbtdocker.DockerPushException: Could not parse Docker image digest

**Comment by ItgLvb** [comment]
https://github.com/marcuslonnberg/sbt-docker/pull/135
