### ISSUE TITLE
Error building image

### ISSUE THREAD

**Issue by rodant** [marcuslonnberg/sbt-docker#42]
Hello, 

I write this issue because I haven't found any solution in the net.

I've been trying to pack my play app in a docker container using sbt-docker and the docker task is failing. Right after the plugin starts docker I get the trace before. Maybe the is the plugin incompatible with my docker version? I'm using "se.marcuslonnberg" % "sbt-docker" % "1.3.0" and sbt 0.13.9.

Thanks in advance,
Antonio.

[debug] Building Dockerfile:
[debug] FROM frolvlad/alpine-oraclejdk8:slim
[debug] COPY 0/stage /app
[debug] ENTRYPOINT ["\/app\/stage\/bin\/server"]
[debug] EXPOSE 9000 2549
[debug] Preparing stage directory '/home/antonio/Dropbox/sparkmind_code/sparkmind-web/server/target/docker'
[debug] Running command: 'docker build --no-cache=false --rm=true --pull=false .' in '/home/antonio/Dropbox/sparkmind_code/sparkmind-web/server/target/docker'
[info] docker - version 1.4
[info] Copyright 2003, Ben Jansens <ben@orodu.net>
[info] 
[info] Usage: docker [OPTIONS]
[info] 
[info] Options:
[info]   -help             Show this help.
[info]   -display DISPLAY  The X display to connect to.
[info]   -border           The width of the border to put around the
[info]                     system tray icons. Defaults to 1.
[info]   -vertical         Line up the icons vertically. Defaults to
[info]                     horizontally.
[info]   -wmaker           WindowMaker mode. This makes docker a
[info]                     fixed size (64x64) to appear nicely in
[info]                     in WindowMaker.
[info]                     Note: In this mode, you have a fixed
[info]                     number of icons that docker can hold.
[info]   -iconsize SIZE    The size (width and height) to display
[info]                     icons as in the system tray. Defaults to
[info]                     24.
[info]   -color COLOR      The background color to use for the tray.
[info]                     Defaults to whatever color the window
[info]                     manager specifies.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.process.BasicIO$Streamed$.scala$sys$process$BasicIO$Streamed$$next$1(BasicIO.scala:48)
        at scala.sys.process.BasicIO$Streamed$$anonfun$scala$sys$process$BasicIO$Streamed$$next$1$1.apply(BasicIO.scala:49)
        at scala.sys.process.BasicIO$Streamed$$anonfun$scala$sys$process$BasicIO$Streamed$$next$1$1.apply(BasicIO.scala:49)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream.foreach(Stream.scala:548)
        at sbtdocker.DockerBuild$.build(DockerBuild.scala:87)
        at sbtdocker.DockerBuild$.buildAndTag(DockerBuild.scala:72)
        at sbtdocker.DockerBuild$.apply(DockerBuild.scala:45)
        at sbtdocker.DockerBuild$.apply(DockerBuild.scala:24)
        at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$1.apply(DockerSettings.scala:17)
        at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$1.apply(DockerSettings.scala:10)

**Comment by rodant** [comment]
Hello again,

sorry, it was my fault. I have the wrong docker package on my system.
