### ISSUE TITLE
Timeout on docker push

### ISSUE THREAD

**Issue by l15k4** [marcuslonnberg/sbt-docker#43]
Hey,

I'm using docker `1.9.1` and tried `sbt-docker 1.2.0 & 1.3.0` and since yesterday I always get this error, I tried like 50 times, but pushing the image directly by `docker push` works every time... Any idea why does it happen only when using `sbt-docker` ?

```
[info] Head https://registry-1.docker.io/v2/gwiq/gwiq-app/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4: dial tcp 54.209.64.176:443: i/o timeout
java.lang.RuntimeException: Failed to push
        at scala.sys.package$.error(package.scala:27)
        at sbtdocker.DockerPush$.apply(DockerPush.scala:42)
        at sbtdocker.DockerPush$$anonfun$apply$1.apply(DockerPush.scala:17)
        at sbtdocker.DockerPush$$anonfun$apply$1.apply(DockerPush.scala:16)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at sbtdocker.DockerPush$.apply(DockerPush.scala:16)
        at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$2.apply(DockerSettings.scala:24)
        at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$2.apply(DockerSettings.scala:19)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by marcuslonnberg** [comment]
@l15k4 is this still a problem for you?
I have never had this problem in my projects.

**Comment by l15k4** [comment]
@marcuslonnberg it was a temporary 2 days problem. There must be a stricter timeouts or smth. like that in Docker API then it is in the docker client...

**Comment by marcuslonnberg** [comment]
@l15k4 ok thanks. Will close this. But reopen/create a new issue if the problem reoccurs.
