### ISSUE TITLE
Error when tagging in sbt-docker 1.4: "flag provided but not defined: -f"

### ISSUE THREAD

**Issue by jletroui** [marcuslonnberg/sbt-docker#49]
This is because DockerVersion assumes there is a "-f" flag in "docker version". This is not the case for docker 1.6.

**Comment by marcuslonnberg** [comment]
We should probably address this, in the meantime use version 1.3.0.

**Comment by mariussoutier** [comment]
1.3.0 has the same issue.

**Comment by toby5box** [comment]
I also hit this, using 1.4.0:

```
2016-07-07T01:41:19.030Zcv_service[info] Tagging image 87ec73468a42 with name: us.gcr.io/xx/cv_service:
2016-07-07T01:41:19.189Zcv_service[info] flag provided but not defined: -f
2016-07-07T01:41:19.190Zcv_service[info] See 'docker version --help'.
2016-07-07T01:41:19.207Zcv_servicejava.lang.RuntimeException: Nonzero exit value: 2
2016-07-07T01:41:19.208Zcv_service	at scala.sys.package$.error(package.scala:27)
2016-07-07T01:41:19.208Zcv_service	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:131)
2016-07-07T01:41:19.208Zcv_service	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerVersion$.apply(DockerVersion.scala:19)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerTag$.apply(DockerTag.scala:17)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerBuild$$anonfun$buildAndTag$1.apply(DockerBuild.scala:75)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerBuild$$anonfun$buildAndTag$1.apply(DockerBuild.scala:74)
2016-07-07T01:41:19.208Zcv_service	at scala.collection.immutable.List.foreach(List.scala:318)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerBuild$.buildAndTag(DockerBuild.scala:74)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:45)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:24)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$1.apply(DockerSettings.scala:17)
2016-07-07T01:41:19.208Zcv_service	at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$1.apply(DockerSettings.scala:10)
2016-07-07T01:41:19.208Zcv_service	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
2016-07-07T01:41:19.208Zcv_service	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
2016-07-07T01:41:19.208Zcv_service	at sbt.std.Transform$$anon$4.work(System.scala:63)
2016-07-07T01:41:19.208Zcv_service	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
2016-07-07T01:41:19.208Zcv_service	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
2016-07-07T01:41:19.208Zcv_service	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
2016-07-07T01:41:19.209Zcv_service	at sbt.Execute.work(Execute.scala:235)
2016-07-07T01:41:19.209Zcv_service	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
2016-07-07T01:41:19.209Zcv_service	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
2016-07-07T01:41:19.209Zcv_service	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
2016-07-07T01:41:19.209Zcv_service	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
2016-07-07T01:41:19.209Zcv_service	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
2016-07-07T01:41:19.209Zcv_service	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
2016-07-07T01:41:19.209Zcv_service	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
2016-07-07T01:41:19.209Zcv_service	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2016-07-07T01:41:19.209Zcv_service	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2016-07-07T01:41:19.209Zcv_service	at java.lang.Thread.run(Thread.java:745)
2016-07-07T01:41:19.209Zcv_service[error] (*:docker) Nonzero exit value: 2
```

```
# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
```

**Comment by rgruener** [comment]
I have also run into this issue on docker 1.6.2

**Comment by davidxia** [comment]
Same issue on docker 1.7.x

**Comment by ken-em** [comment]
@jletroui @kurtkopchik Just do another recursive call to `DockerVersion` here https://github.com/marcuslonnberg/sbt-docker/commit/03bc0c27eff00d8625c6007f7c67fa01ae0e9e55#diff-6a4afe4dda088d1364aa14dd812d58d8R18 to figure out the docker version! Done.

**Comment by tkhduracell** [comment]
Any progress?

**Comment by marcuslonnberg** [comment]
I'm using the latest version of Docker, so I can't reproduce this.

If you are able to please submit a PR for this.
