### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by stefanobaghino** [marcuslonnberg/sbt-docker#55]
`docker version: ....... 1.12.1, build 23cf638`
`sbt-docker version: ... 1.4.0`
`sbt version: .......... 0.13.11`
`scala version: ........ 2.11.7`
`java version: ......... openjdk "1.8.0_91"`
`os: ................... Ubuntu 16.04.1 LTS`

I'm currently trying to build and push an image to a plain HTTP registry.
I've followed the instructions provided [here](https://docs.docker.com/registry/insecure/#/deploying-a-plain-http-registry) to do so but the following error occurs when running `sbt dockerBuildAndPush` (strings within braces have been redacted):
```
[info] Successfully built {SHA}
[info] Tagging image {SHA} with name: {REG}/{NS}/{IMAGE}:{TAG1}
[info] Tagging image {SHA} with name: {REG}/{NS}/{IMAGE}:{TAG2}
[info] Tagging image {SHA} with name: {REG}/{NS}/{IMAGE}:{TAG3}
[info] Pushing docker image with name: '{REG}/{NS}/{IMAGE}:{TAG1}
[info] The push refers to a repository [{REG}/{NS}/{IMAGE}]
[info] Get https://{REG}/v1/_ping: http: server gave HTTP response to HTTPS client
java.lang.RuntimeException: Failed to push
	at scala.sys.package$.error(package.scala:27)
	at sbtdocker.DockerPush$.apply(DockerPush.scala:42)
	at sbtdocker.DockerPush$$anonfun$apply$1.apply(DockerPush.scala:17)
	at sbtdocker.DockerPush$$anonfun$apply$1.apply(DockerPush.scala:16)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at sbtdocker.DockerPush$.apply(DockerPush.scala:16)
	at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$2.apply(DockerSettings.scala:24)
	at sbtdocker.DockerSettings$$anonfun$baseDockerSettings$2.apply(DockerSettings.scala:19)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stefanobaghino** [comment]
My mistake, unfortunately I failed to read the docs properly and used the wrong configuration file. [This blog post](http://www.developmentalmadness.com/2016/03/09/docker-configure-insecure-registry-for-systemd/) helped me configuring my `dockerd` to push to a plain HTTP registry on a `system.d`-based system.

To solve:
* create the file `/etc/systemd/system/docker.service.d/docker.conf` with the following content:

        [Service]
        ExecStart=
        ExecStart=/usr/bin/docker daemon -H fd:// --insecure-registry={REG}

* reload the configuration and restart `dockerd`

        sudo systemctl daemon-reload
        sudo systemctl restart docker
