### ISSUE TITLE
dockerBuildAndPush does not log

### ISSUE THREAD

**Issue by david-mcgillicuddy-ovo** [marcuslonnberg/sbt-docker#82]
Hi, when running `sbt dockerBuildAndPush` I was unable to get the output of any logs i.e. the process just fails with:
```
[info] Tagging image <image> with name: <name>
[error] java.lang.RuntimeException: Failed to push
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbtdocker.DockerPush$.apply(DockerPush.scala:42)
```

However switching to `sbt docker dockerPush` then the logs output just fine and I'm using this workaround for now.

I believe the problem might be that `dockerBuildAndPush` doesn't have a log stream defined although `docker` and `dockerPush` both do:
https://github.com/marcuslonnberg/sbt-docker/blob/master/src/main/scala/sbtdocker/DockerSettings.scala#L27

**Comment by marcuslonnberg** [comment]
Looking at the stacktrace it seems that the `docker` binary exited with a non zero exit code.
https://github.com/marcuslonnberg/sbt-docker/blob/master/src/main/scala/sbtdocker/DockerPush.scala#L42
